server:
    port: 8073
    
mybatis.mapper-locations: classpath:com/eason/**/*.xml

spring:
    datasource:
        name: dataSource
        url: jdbc:mysql://10.20.25.230:3306/user
        username: root
        password: eason
        connectionProperties: config.decrypt=false
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: config,stat
        maxWait: 60000
        maxActive: 20
        initialSize: 1
        minIdle: 1
        validationQuery: select 1
        testWhileIdle: true
        poolPreparedStatements: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: false
        testOnReturn: false
        logSlowSql: true
        
logging.level.root: INFO
logging.level.org.springframework.web: WARN
logging.level.com.eason: INFO

#spring.data.mongodb.uri:  mongodb://eason:eason@10.10.4.230:27017/lottery

---
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
  - "redis://10.20.25.230:7001"
  - "redis://10.20.25.230:7002"
  - "redis://10.20.25.230:7003"
  - "redis://10.20.25.230:7004"
  - "redis://10.20.25.230:7005"
  - "redis://10.20.25.230:7006"
  scanInterval: 1000
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

