server:
    port: 8073
    
mybatis.mapper-locations: classpath:com/eason/**/*.xml

spring:
    datasource:
        name: dataSource
        url: jdbc:mysql://10.20.25.230:3306/user
        username: root
        password: eason
        connectionProperties: config.decrypt=false
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: config,stat
        maxWait: 60000
        maxActive: 20
        initialSize: 1
        minIdle: 1
        validationQuery: select 1
        testWhileIdle: true
        poolPreparedStatements: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: false
        testOnReturn: false
        logSlowSql: true
        
logging.level.root: INFO
logging.level.org.springframework.web: WARN
logging.level.com.eason: INFO

#spring.data.mongodb.uri:  mongodb://eason:eason@10.10.4.230:27017/lottery

